import { BankData, StemData, TrackData, AppSettings, MasterEqPresetConfig } from './types';

export const INITIAL_STEMS: StemData[] = [
  {
    id: 'drums',
    name: 'DRUMS',
    colorName: 'White / Mono',
    accentColor: '#f4f4f5',
    glowClass: 'shadow-[0_0_12px_rgba(244,244,245,0.4)]',
    textClass: 'text-zinc-100',
    bgClass: 'bg-zinc-100',
    volume: 0.82,
    mute: false,
    solo: false,
    cue: false,
    filter: 0.5,
    pan: 0,
    eq: { low: 0, mid: 0, high: 0 },
    level: 0.76,
    send: 0.25,
  },
  {
    id: 'bass',
    name: 'BASS',
    colorName: 'Cool Blue',
    accentColor: '#38bdf8',
    glowClass: 'shadow-[0_0_12px_rgba(56,189,248,0.4)]',
    textClass: 'text-sky-400',
    bgClass: 'bg-sky-400',
    volume: 0.71,
    mute: false,
    solo: false,
    cue: false,
    filter: 0.5,
    pan: 0,
    eq: { low: 1.5, mid: -0.5, high: 0 },
    level: 0.68,
    send: 0.15,
  },
  {
    id: 'music',
    name: 'MUSIC',
    colorName: 'Mint / Green',
    accentColor: '#4ade80',
    glowClass: 'shadow-[0_0_12px_rgba(74,222,128,0.4)]',
    textClass: 'text-emerald-400',
    bgClass: 'bg-emerald-400',
    volume: 0.64,
    mute: false,
    solo: false,
    cue: false,
    filter: 0.5,
    pan: 0,
    eq: { low: -1.0, mid: 1.0, high: 0.5 },
    level: 0.58,
    send: 0.40,
  },
  {
    id: 'vocal',
    name: 'VOCAL',
    colorName: 'Warm Peach / Orange',
    accentColor: '#fb923c',
    glowClass: 'shadow-[0_0_12px_rgba(251,146,60,0.4)]',
    textClass: 'text-orange-400',
    bgClass: 'bg-orange-400',
    volume: 0.48,
    mute: false,
    solo: false,
    cue: false,
    filter: 0.5,
    pan: 0,
    eq: { low: -2.0, mid: 2.0, high: 1.0 },
    level: 0.44,
    send: 0.55,
  },
];

export const INITIAL_BANKS: BankData = {
  A: {
    mode: 'HOT CUE',
    pads: [
      { id: 0, label: 'CUE 1', sublabel: 'INTRO', color: 'drums', active: true, type: 'cue', value: 0 },
      { id: 1, label: 'CUE 2', sublabel: 'BUILD', color: 'bass', active: true, type: 'cue', value: 30 },
      { id: 2, label: 'CUE 3', sublabel: 'DROP', color: 'music', active: true, type: 'cue', value: 60 },
      { id: 3, label: 'CUE 4', sublabel: 'VOX HOOK', color: 'vocal', active: true, type: 'cue', value: 90 },
      { id: 4, label: 'CUE 5', sublabel: 'BREAK', color: 'accent', active: false, type: 'cue', value: 120 },
      { id: 5, label: 'CUE 6', sublabel: 'PEAK', color: 'music', active: true, type: 'cue', value: 154 },
      { id: 6, label: 'CUE 7', sublabel: 'SUB ROLL', color: 'bass', active: false, type: 'cue', value: 184 },
      { id: 7, label: 'CUE 8', sublabel: 'OUTRO', color: 'drums', active: true, type: 'cue', value: 214 },
      { id: 8, label: 'LOOP 1/4', sublabel: 'STUTTER', color: 'muted', active: false, type: 'loop', value: 0.25 },
      { id: 9, label: 'LOOP 1/2', sublabel: 'HALF', color: 'muted', active: false, type: 'loop', value: 0.5 },
      { id: 10, label: 'LOOP 1', sublabel: 'BEAT', color: 'muted', active: false, type: 'loop', value: 1 },
      { id: 11, label: 'LOOP 2', sublabel: 'BAR', color: 'muted', active: false, type: 'loop', value: 2 },
      { id: 12, label: 'LOOP 4', sublabel: 'SECTION', color: 'muted', active: false, type: 'loop', value: 4 },
      { id: 13, label: 'LOOP 8', sublabel: 'PHRASE', color: 'muted', active: false, type: 'loop', value: 8 },
      { id: 14, label: 'LOOP 16', sublabel: 'FULL', color: 'muted', active: false, type: 'loop', value: 16 },
      { id: 15, label: 'LOOP 32', sublabel: 'EXTENDED', color: 'muted', active: false, type: 'loop', value: 32 },
    ],
  },
  B: {
    mode: 'SLICER',
    pads: [
      { id: 0, label: 'SL 1', sublabel: 'KICK 1', color: 'drums', active: true, type: 'slice', value: 0 },
      { id: 1, label: 'SL 2', sublabel: 'HAT', color: 'drums', active: false, type: 'slice', value: 1 },
      { id: 2, label: 'SL 3', sublabel: 'SUB GLIDE', color: 'bass', active: true, type: 'slice', value: 2 },
      { id: 3, label: 'SL 4', sublabel: 'SYNTH HIT', color: 'music', active: false, type: 'slice', value: 3 },
      { id: 4, label: 'SL 5', sublabel: 'CLAP', color: 'drums', active: true, type: 'slice', value: 4 },
      { id: 5, label: 'SL 6', sublabel: 'HAT OPEN', color: 'drums', active: false, type: 'slice', value: 5 },
      { id: 6, label: 'SL 7', sublabel: 'VOX CHOP', color: 'vocal', active: true, type: 'slice', value: 6 },
      { id: 7, label: 'SL 8', sublabel: 'SUB PUNCH', color: 'bass', active: false, type: 'slice', value: 7 },
      { id: 8, label: 'SL 9', sublabel: 'KICK 2', color: 'drums', active: true, type: 'slice', value: 8 },
      { id: 9, label: 'SL 10', sublabel: 'SYNTH 2', color: 'music', active: false, type: 'slice', value: 9 },
      { id: 10, label: 'SL 11', sublabel: 'CLAP ROLL', color: 'drums', active: true, type: 'slice', value: 10 },
      { id: 11, label: 'SL 12', sublabel: 'CHORD STAB', color: 'music', active: false, type: 'slice', value: 11 },
      { id: 12, label: 'SL 13', sublabel: 'VOX SHOUT', color: 'vocal', active: true, type: 'slice', value: 12 },
      { id: 13, label: 'SL 14', sublabel: 'SUB FILTER', color: 'bass', active: false, type: 'slice', value: 13 },
      { id: 14, label: 'SL 15', sublabel: 'RISER HIT', color: 'accent', active: false, type: 'slice', value: 14 },
      { id: 15, label: 'SL 16', sublabel: 'TURNAROUND', color: 'drums', active: true, type: 'slice', value: 15 },
    ],
  },
  C: {
    mode: 'ROLL',
    pads: [
      { id: 0, label: 'ROLL 1/32', sublabel: 'DRILL', color: 'drums', active: false, type: 'roll', value: 0.03125 },
      { id: 1, label: 'ROLL 1/16', sublabel: 'SNARE', color: 'drums', active: false, type: 'roll', value: 0.0625 },
      { id: 2, label: 'ROLL 1/8', sublabel: 'KICK', color: 'drums', active: false, type: 'roll', value: 0.125 },
      { id: 3, label: 'ROLL 1/4', sublabel: 'QUARTER', color: 'drums', active: false, type: 'roll', value: 0.25 },
      { id: 4, label: 'ROLL 1/2', sublabel: 'HALF BEAT', color: 'bass', active: false, type: 'roll', value: 0.5 },
      { id: 5, label: 'ROLL 1', sublabel: 'FULL BEAT', color: 'bass', active: false, type: 'roll', value: 1 },
      { id: 6, label: 'ROLL 2', sublabel: 'HALF BAR', color: 'music', active: false, type: 'roll', value: 2 },
      { id: 7, label: 'ROLL 4', sublabel: 'BAR ROLL', color: 'music', active: false, type: 'roll', value: 4 },
      { id: 8, label: 'TRIPLET 1/32T', sublabel: 'SWING', color: 'vocal', active: false, type: 'roll', value: 0.02 },
      { id: 9, label: 'TRIPLET 1/16T', sublabel: 'TRIPLET', color: 'vocal', active: false, type: 'roll', value: 0.0416 },
      { id: 10, label: 'TRIPLET 1/8T', sublabel: 'BOUNCE', color: 'accent', active: false, type: 'roll', value: 0.0833 },
      { id: 11, label: 'TRIPLET 1/4T', sublabel: 'SLOW TRIP', color: 'accent', active: false, type: 'roll', value: 0.166 },
      { id: 12, label: 'TAPE STOP', sublabel: 'BRAKE', color: 'muted', active: false, type: 'roll', value: 0 },
      { id: 13, label: 'WASH OUT', sublabel: 'REVERB TAIL', color: 'muted', active: false, type: 'roll', value: 0 },
      { id: 14, label: 'FILTER GLITCH', sublabel: 'BANDPASS', color: 'muted', active: false, type: 'roll', value: 0 },
      { id: 15, label: 'CRUSH DROP', sublabel: '8-BIT BITCRUSH', color: 'muted', active: false, type: 'roll', value: 0 },
    ],
  },
  D: {
    mode: 'HOT CUE',
    pads: [
      { id: 0, label: 'STEM MUTE', sublabel: 'DRUM KILL', color: 'drums', active: false, type: 'cue', value: 0 },
      { id: 1, label: 'STEM MUTE', sublabel: 'BASS KILL', color: 'bass', active: false, type: 'cue', value: 0 },
      { id: 2, label: 'STEM MUTE', sublabel: 'MUSIC KILL', color: 'music', active: false, type: 'cue', value: 0 },
      { id: 3, label: 'STEM MUTE', sublabel: 'VOX KILL', color: 'vocal', active: false, type: 'cue', value: 0 },
      { id: 4, label: 'SOLO STEM', sublabel: 'DRUM SOLO', color: 'drums', active: false, type: 'cue', value: 0 },
      { id: 5, label: 'SOLO STEM', sublabel: 'BASS SOLO', color: 'bass', active: false, type: 'cue', value: 0 },
      { id: 6, label: 'SOLO STEM', sublabel: 'SYNTH SOLO', color: 'music', active: false, type: 'cue', value: 0 },
      { id: 7, label: 'SOLO STEM', sublabel: 'ACAPELLA', color: 'vocal', active: false, type: 'cue', value: 0 },
      { id: 8, label: 'CUE A1', sublabel: 'TRANSITION A', color: 'white', active: true, type: 'cue', value: 45 },
      { id: 9, label: 'CUE B1', sublabel: 'PEAK MOMENT', color: 'accent', active: true, type: 'cue', value: 105 },
      { id: 10, label: 'CUE C1', sublabel: 'STRIPPED', color: 'music', active: true, type: 'cue', value: 165 },
      { id: 11, label: 'CUE D1', sublabel: 'FINAL DROP', color: 'vocal', active: true, type: 'cue', value: 195 },
      { id: 12, label: 'RISER FX', sublabel: '16 BEAT BUILD', color: 'accent', active: false, type: 'cue', value: 0 },
      { id: 13, label: 'SUB DROP', sublabel: '808 IMPACT', color: 'bass', active: false, type: 'cue', value: 0 },
      { id: 14, label: 'SIREN', sublabel: 'DUB SIREN', color: 'music', active: false, type: 'cue', value: 0 },
      { id: 15, label: 'AIR HORN', sublabel: 'SOUNDCLASH', color: 'drums', active: false, type: 'cue', value: 0 },
    ],
  },
};

export const TRACK_CATALOG: TrackData[] = [
  {
    id: 'track-1',
    title: 'Lost Control (Original Mix)',
    artist: 'HAMMERSTEYN',
    bpm: 128.0,
    key: '8A',
    duration: 252, // 04:12
    genre: 'Peak Time Techno',
    stems: { drums: true, bass: true, music: true, vocal: true },
    waveform: [15, 25, 45, 60, 75, 90, 85, 95, 100, 70, 85, 90, 95, 60, 40, 25, 50, 75, 90, 95, 100, 80, 65, 45, 30, 20, 10],
    peakDb: -0.3,
    peakRmsDb: -12.4,
    gainCompensationDb: -1.6,
  },
  {
    id: 'track-2',
    title: 'Elevate',
    artist: 'Tech House Collective',
    bpm: 125.0,
    key: '7A',
    duration: 303, // 05:03
    genre: 'Tech House',
    stems: { drums: true, bass: true, music: true, vocal: true },
    waveform: [20, 35, 55, 65, 80, 85, 90, 95, 80, 65, 75, 85, 90, 70, 50, 35, 60, 80, 90, 95, 85, 70, 55, 40, 25, 15],
    peakDb: -0.8,
    peakRmsDb: -15.4,
    gainCompensationDb: 1.4,
  },
  {
    id: 'track-3',
    title: 'Night Drive',
    artist: 'Melodic Techno Unit',
    bpm: 126.0,
    key: '9A',
    duration: 381, // 06:21
    genre: 'Melodic Techno',
    stems: { drums: true, bass: true, music: true, vocal: true },
    waveform: [10, 20, 35, 50, 70, 85, 90, 95, 100, 85, 90, 95, 100, 90, 75, 55, 40, 65, 85, 95, 90, 75, 60, 40, 25, 15],
    peakDb: -1.2,
    peakRmsDb: -16.8,
    gainCompensationDb: 2.8,
  },
  {
    id: 'track-4',
    title: 'Push',
    artist: 'Minimal Sound System',
    bpm: 129.0,
    key: '8A',
    duration: 318, // 05:18
    genre: 'Minimal / Deep',
    stems: { drums: true, bass: true, music: true, vocal: true },
    waveform: [15, 30, 45, 60, 70, 80, 85, 90, 75, 60, 70, 80, 85, 65, 50, 35, 55, 75, 85, 90, 80, 65, 45, 30, 20, 10],
    peakDb: -0.5,
    peakRmsDb: -13.8,
    gainCompensationDb: -0.2,
  },
  {
    id: 'track-5',
    title: 'Fragments',
    artist: 'Deep Tech Syndicate',
    bpm: 124.0,
    key: '6A',
    duration: 276, // 04:36
    genre: 'Deep Tech',
    stems: { drums: true, bass: true, music: true, vocal: true },
    waveform: [20, 40, 60, 75, 85, 90, 85, 95, 80, 65, 75, 85, 90, 75, 55, 40, 60, 80, 90, 95, 85, 70, 50, 35, 20, 10],
    peakDb: -1.8,
    peakRmsDb: -17.5,
    gainCompensationDb: 3.5,
  },
];

export const MASTER_EQ_PRESETS: MasterEqPresetConfig[] = [
  {
    id: 'club',
    name: 'Club',
    description: 'Punchy low-end kick & crisp highs for sound system power',
    eq: { low: 3.5, mid: -1.0, high: 2.5 },
  },
  {
    id: 'vocal',
    name: 'Vocal',
    description: 'Vocal presence & intelligibility with low-end cut',
    eq: { low: -2.0, mid: 3.5, high: 2.0 },
  },
  {
    id: 'bass_heavy',
    name: 'Bass Heavy',
    description: 'Maximum sub-bass drive and heavy low-frequency punch',
    eq: { low: 6.0, mid: -1.5, high: 0.0 },
  },
  {
    id: 'flat',
    name: 'Flat',
    description: 'Linear 0 dB studio reference with zero coloration',
    eq: { low: 0.0, mid: 0.0, high: 0.0 },
  },
  {
    id: 'warm_analog',
    name: 'Warm Analog',
    description: 'Gentle high-shelf roll-off with saturated low-mid body',
    eq: { low: 2.5, mid: 1.0, high: -2.0 },
  },
  {
    id: 'bright_air',
    name: 'Bright Air',
    description: 'Sparkling high-frequency sheen and open top-end brilliance',
    eq: { low: 0.0, mid: 1.5, high: 4.5 },
  },
  {
    id: 'smiley',
    name: 'Smiley Curve',
    description: 'Classic V-shaped curve with scooped mids and boosted peaks',
    eq: { low: 4.0, mid: -2.5, high: 4.0 },
  },
];

export const DEFAULT_SETTINGS: AppSettings = {
  audioDevice: 'Default System Output (2ch)',
  latency: 'LOW (128)',
  faderCurve: 'Linear',
  masterLimiter: true,
  padSensitivity: 'HIGH',
  padQuantize: '1/16',
  stemEngine: 'NEURAL 4-WAY V2',
  bpmDetection: true,
  autoBpm: true,
  keyFormat: 'CAMELOT',
  brightness: 100,
  theme: 'NOTHING_DARK',
  glyphIntensity: 'MEDIUM',
  hardwareMode: false,
  masterEq: {
    low: 3.5,
    mid: -1.0,
    high: 2.5,
  },
  masterEqPreset: 'Club',
  uiSounds: true,
  showBeatGridOverlay: true,
  hapticFeedback: true,
};
